### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by malandiwang** [StoneLeon/STLBGVideo#1]
为什么导进项目视频不会循环播放？

**Comment by StoneLeon** [comment]
plist文件中有一个设置循环的bool值.你看下.

**Comment by malandiwang** [comment]
设置的是yes，但是不行，换成no也不行
是不是因为其他原因？

**Comment by StoneLeon** [comment]
你看下可能是不是视频的问题,换个视频尝试下,这边好多朋友也是这样用的,还没出现跟你一样的问题. 还解决不了,如果方便的话,可以把文件发给我,我帮你看下到底什么问题.

**Comment by malandiwang** [comment]
好的，谢谢，我换个视频试试
其他地方不需要设置什么吧？

**Comment by malandiwang** [comment]
对了，可以问你一下，你的这些短小的视频使用什么制作的呢？AE吗？
